* config
#+BEGIN_SRC emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+END_SRC

* who i am
#+BEGIN_SRC emacs-lisp
(setq user-full-name "chaomai"
      user-mail-address "loneymai@gmail.com")
#+END_SRC

* basic
** clipboard
Setup copy paste based on platform. The Windows wsl2 use powershell to accomplish paste, which is a bit of slow.

[[https://stackoverflow.com/questions/64360/how-to-copy-text-from-emacs-to-another-application-on-linux][How to copy text from Emacs to another application on Linux]]

#+BEGIN_SRC emacs-lisp
(defun wsl2-copy (beg end)
  (interactive "r")
  (call-process-region beg end "clip.exe"))

(defun wsl2-paste ()
  (interactive)
  (if (region-active-p) (delete-region (region-beginning) (region-end)) nil)
  (call-process "powershell.exe" nil t nil "-Command" "Get-Clipboard"))

(defun osx-copy (beg end)
  (interactive "r")
  (call-process-region beg end "pbcopy"))

(defun osx-paste ()
  (interactive)
  (if (region-active-p) (delete-region (region-beginning) (region-end)) nil)
  (call-process "pbpaste" nil t nil))

(defun linux-copy (beg end)
  (interactive "r")
  (call-process-region beg end "xclip" nil nil nil "-selection" "c"))

(defun linux-paste ()
  (interactive)
  (if (region-active-p) (delete-region (region-beginning) (region-end)) nil)
  (call-process "xsel" nil t nil "-b"))

(cond
 ((string-equal system-type "darwin")
  (define-key global-map (kbd "C-x C-y") 'osx-copy)
  (define-key global-map (kbd "C-x C-p") 'osx-paste))

 ((string-equal system-type "gnu/linux")
  (define-key global-map (kbd "C-x C-y") 'linux-copy)
  (define-key global-map (kbd "C-x C-p") 'linux-paste))

 ((string-match "microsoft"
                (with-temp-buffer (shell-command "uname -r" t)
                                  (goto-char (point-max))
                                  (delete-char -1)
                                  (buffer-string)))
  (define-key global-map (kbd "C-x C-y") 'wsl2-copy)
  (define-key global-map (kbd "C-x C-p") 'wsl2-paste)))
#+END_SRC

** history
#+BEGIN_SRC emacs-lisp
(setq-default history-length 1000)
#+END_SRC

** projecttile
Project root is same with vim's configuration.

#+BEGIN_SRC emacs-lisp
(setq projectile-require-project-root t)
(setq projectile-project-root-files '(".ccls-root" ".idea" "go.mod" ".bzr" "_darcs"
                                      "build.xml" ".project" ".root" ".svn" ".git"
                                      "index.org"))

(setq projectile-project-root-files-functions '(projectile-root-top-down
                                                projectile-root-top-down-recurring
                                                projectile-root-bottom-up
                                                projectile-root-local))
#+END_SRC

* ui
** basic
Prevents some cases of Emacs flickering.

#+BEGIN_SRC emacs-lisp
(add-to-list 'default-frame-alist '(inhibit-double-buffering . t))
#+END_SRC

** font
Doom exposes five (optional) variables for controlling fonts in Doom. Here are the three important ones:
1. `doom-font'
2. `doom-variable-pitch-font'
3. `doom-big-font' -- used for `doom-big-font-mode'; use this for presentations or streaming.

They all accept either a font-spec, font string ("Input Mono-12"), or xlfd font string. You generally only need these two:

#+BEGIN_SRC emacs-lisp
(cond
 ((string-equal system-type "darwin")
  (setq doom-font (font-spec :family "Fira Code" :size 13 :weight 'regular)))

 ((string-match "microsoft"
                (with-temp-buffer (shell-command "uname -r" t)
                                  (goto-char (point-max))
                                  (delete-char -1)
                                  (buffer-string)))
  (setq doom-font (font-spec :family "Fira Code" :size 18 :weight 'regular))))
#+END_SRC

** color theme
There are two ways to load a theme. Both assume the theme is installed and available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function.

#+BEGIN_SRC emacs-lisp
;; (setq doom-theme 'doom-one)

(setq doom-theme 'spacemacs-dark
      spacemacs-theme-comment-bg nil
      spacemacs-theme-comment-italic t)
#+END_SRC

** line spacing
#+BEGIN_SRC emacs-lisp
(setq-default line-spacing 5)
#+END_SRC

** line numbers
This determines the style of line numbers in effect.
1. If set to `nil', line numbers are disabled.
2. For relative line numbers, set this to `relative'.

#+BEGIN_SRC emacs-lisp
;; (setq display-line-numbers-type nil)
#+END_SRC

** awesome-tab
#+BEGIN_SRC emacs-lisp
;; (use-package! awesome-tab
;;   :config
;;   (awesome-tab-mode t)
;;   (setq awesome-tab-show-tab-index t
;;         awesome-tab-height 120)
;; 
;;   (defun my-select-window ()
;;     (interactive)
;;     (let* ((event last-input-event)
;;            (key (make-vector 1 event))
;;            (key-desc (key-description key)))
;;       (my-select-window-by-number
;;        (string-to-number (car (nreverse (split-string key-desc "-"))))))))
;; 
;; (global-set-key (kbd "M-1") 'awesome-tab-select-visible-tab)
;; (global-set-key (kbd "M-2") 'awesome-tab-select-visible-tab)
;; (global-set-key (kbd "M-3") 'awesome-tab-select-visible-tab)
;; (global-set-key (kbd "M-4") 'awesome-tab-select-visible-tab)
;; (global-set-key (kbd "M-5") 'awesome-tab-select-visible-tab)
;; (global-set-key (kbd "M-6") 'awesome-tab-select-visible-tab)
;; (global-set-key (kbd "M-7") 'awesome-tab-select-visible-tab)
;; (global-set-key (kbd "M-8") 'awesome-tab-select-visible-tab)
;; (global-set-key (kbd "M-9") 'awesome-tab-select-visible-tab)
;; (global-set-key (kbd "M-0") 'awesome-tab-select-visible-tab)
#+END_SRC

* company
** basic
#+BEGIN_SRC emacs-lisp
(use-package! company
  :config
  (setq company-idle-delay 0.1))
#+END_SRC

* ivy
[[https://writequit.org/denver-emacs/presentations/2017-04-11-ivy.html][Ivy, Counsel and Swiper]]

#+BEGIN_SRC emacs-lisp
(use-package ivy
  :config
  (setq ivy-display-style 'fancy
        ivy-count-format "(%d/%d) "
        ivy-use-virtual-buffers t
        ivy-on-del-error-function 'ignore
        ivy-re-builders-alist '((t . ivy--regex-fuzzy))))
#+END_SRC

* org-mode
** basic
#+BEGIN_SRC emacs-lisp
(use-package ivy
  :config
  (setq org-directory "~/org/"
        org-ellipsis " ➤ "
        org-superstar-headline-bullets-list '("☰" "☱" "☲" "☳" "☴" "☵" "☶" "☷" "☷" "☷" "☷")
        ;; gdt task status
        org-todo-keywords '((sequence "TODO(t)" "NEXT(n)" "WAITTING(w)" "SOMEDAY(s)" "|" "DONE(d@/!)" "ABORT(a@/!)")
                            (sequence "REPORT(r)" "BUG(b)" "KNOWNCAUSE(k)" "|" "FIXED(f)"))
        ;; 配置归档文件的名称和 Headline 格式。
        org-archive-location "%s_archive::date-tree"))
#+END_SRC

** org agenda
org agenda 里面时间块彩色显示。[[https://emacs-china.org/t/org-agenda/8679/3][Org agenda 显示时间块]]

#+BEGIN_SRC emacs-lisp
;; (defun org-agenda-time-grid-spacing ()
;;   "Set different line spacing w.r.t. time duration."
;;   (save-excursion
;;     (let* ((background (alist-get 'background-mode (frame-parameters)))
;;            (background-dark-p (string= background "dark"))
;;            (colors (list "#1ABC9C" "#2ECC71" "#3498DB" "#9966ff"))
;;            pos
;;            duration)
;;       (nconc colors colors)
;;       (goto-char (point-min))
;;       (while (setq pos (next-single-property-change (point) 'duration))
;;         (goto-char pos)
;;         (when (and (not (equal pos (point-at-eol)))
;;                    (setq duration (org-get-at-bol 'duration)))
;;           (let ((line-height (if (< duration 30) 1.0 (+ 0.5 (/ duration 60))))
;;                 (ov (make-overlay (point-at-bol) (1+ (point-at-eol)))))
;;             (overlay-put ov 'face `(:background ,(car colors)
;;                                                 :foreground
;;                                                 ,(if background-dark-p "black" "white")))
;;             (setq colors (cdr colors))
;;             (overlay-put ov 'line-height line-height)
;;             (overlay-put ov 'line-spacing (1- line-height))))))))

;; (add-hook 'org-agenda-finalize-hook #'org-agenda-time-grid-spacing)
#+END_SRC

** org-download
make drag-and-drop image save in the same name folder as org file.
example: `aa-bb-cc.org' then save image test.png to `aa-bb-cc_media/test.png'.

[[https://coldnew.github.io/hexo-org-example/2018/05/22/use-org-download-to-drag-image-to-emacs/][Use org-download to drag image to emacs]]

#+BEGIN_SRC emacs-lisp
(use-package! org-download
  :after org
  :hook ('dired-mode-hook 'org-download-enable)
  :config
  (defun my-org-download-method (link)
    (let ((filename
           (file-name-nondirectory
            (car (url-path-and-query
                  (url-generic-parse-url link)))))
          (dirname (concat (file-name-sans-extension (buffer-name)) "_media")))
      ;; if directory not exist, create it
      (unless (file-exists-p dirname)
        (make-directory dirname))
      ;; return the path to save the download files
      (expand-file-name filename dirname)))

  (setq org-download-method 'my-org-download-method))
#+END_SRC

* programming
** format
1. c/cpp: clang-format
2. python: black

#+BEGIN_SRC emacs-lisp
;; (after! format
;;   (set-formatter! 'clang-format
;;     '("clang-format"
;;       "-style={BasedOnStyle: Google, SortIncludes: false}"
;;       ("-assume-filename=%S" (or buffer-file-name mode-result "")))
;;     ))

;; :modes
;; '((c-mode ".c")
;;   (c++-mode ".cpp")
;;   (java-mode ".java")
;;   (objc-mode ".m")
;;   (protobuf-mode ".proto"))))

;; (after! format
;;  (set-formatter!
;;    'black "black -q -" :modes '(python-mode)))
#+END_SRC

** lsp basic
lsp-ui-sideline is redundant with eldoc and much more invasive, so disable it by default.

#+BEGIN_SRC emacs-lisp
;; (setq lsp-ui-sideline-enable nil
;;       lsp-enable-symbol-highlighting nil)
#+END_SRC

** c/cpp
*** lsp
Using [[https://github.com/maskray/ccls/][ccls]] as language protocol server.

1. [[https://github.com/MaskRay/Config/blob/master/home/.config/doom/modules/private/my-cc/autoload.el][MaskRay/Config/blob/master/home/.config/doom/modules/private/my-cc/autoload.el]]
2. [[https://github.com/MaskRay/ccls/wiki/lsp-mode][lsp-mode]]

#+BEGIN_SRC emacs-lisp
(use-package! ccls
  :config
  (setq ccls-sem-highlight-method 'font-lock)
  (add-hook 'lsp-after-open-hook #'ccls-code-lens-mode)
  (ccls-use-default-rainbow-sem-highlight)

  (setq ccls-executable "~/Documents/workspace/github/ccls/Release/ccls"
        ccls-args '("--log-file=/tmp/ccls-emacs.log")
        ccls-initialization-options `(:capabilities (:foldingRangeProvider :json-false)
                                                    :cache (:directory ".ccls-cache")
                                                    :completion (:caseSensitivity 0)
                                                    :compilationDatabaseDirectory "cmake-build"
                                                    ;; :codeLens (:localVariables :json-false)
                                                    :client (:snippetSupport t)
                                                    :diagnostics (:onChang 100
                                                                           :onOpen 100
                                                                           :onSave 100)
                                                    :highlight (:lsRanges t)
                                                    :index (:threads 5)))
  (evil-set-initial-state 'ccls-tree-mode 'emacs))
#+END_SRC

*** cpp-font-lock
#+BEGIN_SRC emacs-lisp
(use-package! modern-cpp-font-lock
  :hook (c++-mode . modern-c++-font-lock-mode))
#+END_SRC

* other plugins
** pinyin-search
#+BEGIN_SRC emacs-lisp
(use-package! pinyin-search)
#+END_SRC

** pangu-spacing
#+BEGIN_SRC emacs-lisp
(use-package! pangu-spacing
  :config
  (global-pangu-spacing-mode 1)
  (setq pangu-spacing-real-insert-separtor t))
#+END_SRC

** evil-nerd-commenter
#+BEGIN_SRC emacs-lisp
(use-package! evil-nerd-commenter
  :config
  (evilnc-default-hotkeys))
#+END_SRC

* references
1. [[https://www.gtrun.org/custom/init.html][My Doom Emacs config]]
2. [[https://github.com/condy0919/emacs-newbie][condy0919/emacs-newbie]]
3. [[https://github.com/condy0919/.emacs.d][condy0919/.emacs.d]]
