# zsh performance profile
# zmodload zsh/zprof

# init_home.zsh: setup home

# setup HOME, for shared accout on server
if [[ -s $ZSHRC_DIR/init_home.zsh ]]; then
    source $ZSHRC_DIR/init_home.zsh
fi

# detect os
OSTYPE=$(uname)

# get real path of zshrc
if [[ $OSTYPE == "Darwin" ]]; then
    local cur_path=$(/usr/local/opt/coreutils/libexec/gnubin/readlink -f ${(%):-%x})
else
    local cur_path=$(readlink -f ${(%):-%x})
fi

local ZSHRC_DIR=$(dirname $cur_path)

source $ZSHRC_DIR/init_basic.zsh
source $ZSHRC_DIR/init_config.zsh
source $ZSHRC_DIR/init_plugin.zsh

