# zsh performance profile
# zmodload zsh/zprof

# init_home.zsh: setup home
# init_misc.zsh: add config to overwrite settings

# setup HOME, for shared accout on server
if [[ -s $ZSHRC_DIR/init_home.zsh ]]; then
    source $ZSHRC_DIR/init_home.zsh
fi

# detect os
OSTYPE=$(uname)

# get real path of zshrc
if [[ $OSTYPE == "Darwin" ]]; then
    cur_path=$(/usr/local/opt/coreutils/libexec/gnubin/readlink -f ${(%):-%x})
else
    cur_path=$(readlink -f ${(%):-%x})
fi

ZSHRC_DIR=$(dirname $cur_path)

source $ZSHRC_DIR/init_basic.zsh
source $ZSHRC_DIR/init_config.zsh
source $ZSHRC_DIR/init_plugin.zsh

